name: CD — Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "models/**"

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Debug
        run: echo "Host length = ${#EC2_HOST}"
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /app/backend
            git pull origin main
            cd backend
            docker compose -f docker-compose.yaml up --build -d
            echo "Deployed successfully"
